stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocessing:
    cmd: python -m src.data.data_preprocessing
    deps:
    - data/raw
    - src/data/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python -m src.features.feature_engineering
    deps:
    - data/processed
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/features
  train_model:
    cmd: python -m src.models.train_model
    deps:
    - data/features
    - src/models/train_model.py
    params:
    - model_building.learning_rate
    - model_building.n_estimators
    outs:
    - model.pkl
  model_evaluation:
    cmd: python -m src.models.model_evaluation
    deps:
    - data/features
    - model.pkl
    - src/models/model_evaluation.py
    outs:
    - metrics.json
